### ISSUE TITLE
TypeError: loss_labels() got an unexpected keyword argument 'log'

### ISSUE THREAD

**Issue by Teassassin** [HeinzJiao/PolyR-CNN#3]
I tried to train PolyR-CNN with the following cmd:

```bash
python train_net.py --num-gpus 1 --config-file configs/polyrcnn.res50.100pro.aicrowd.yaml
```

and I got this exception:

```
ERROR [10/22 12:18:13 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/mnt/d/__EXPERIMENTS__/RoIPoly/detectron2/detectron2/engine/train_loop.py", line 155, in train
    self.run_step()
  File "/mnt/d/__EXPERIMENTS__/RoIPoly/detectron2/detectron2/engine/defaults.py", line 530, in run_step
    self._trainer.run_step()
  File "/mnt/d/__EXPERIMENTS__/RoIPoly/detectron2/detectron2/engine/train_loop.py", line 310, in run_step
    loss_dict = self.model(data)
  File "/home/tkk/miniconda3/envs/roipoly_cu111/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/d/__EXPERIMENTS__/PolyR-CNN/polyrcnn/detector.py", line 153, in forward
    loss_dict = self.criterion(output, targets)
  File "/home/tkk/miniconda3/envs/roipoly_cu111/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/d/__EXPERIMENTS__/PolyR-CNN/polyrcnn/loss.py", line 257, in forward
    l_dict = self.get_loss(loss, aux_outputs, targets, indices, **kwargs)
  File "/mnt/d/__EXPERIMENTS__/PolyR-CNN/polyrcnn/loss.py", line 219, in get_loss
    return loss_map[loss](outputs, targets, indices, **kwargs)
TypeError: loss_labels() got an unexpected keyword argument 'log'
[10/22 12:18:13 d2.engine.hooks]: Total training time: 0:00:01 (0:00:00 on hooks)
[10/22 12:18:13 d2.utils.events]:  iter: 0       lr: N/A  max_mem: 5012M
Traceback (most recent call last):
  File "/mnt/d/__EXPERIMENTS__/PolyR-CNN/train_net.py", line 164, in <module>
    launch(
  File "/mnt/d/__EXPERIMENTS__/RoIPoly/detectron2/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/mnt/d/__EXPERIMENTS__/PolyR-CNN/train_net.py", line 158, in main
    return trainer.train()
  File "/mnt/d/__EXPERIMENTS__/RoIPoly/detectron2/detectron2/engine/defaults.py", line 520, in train
    super().train(self.start_iter, self.max_iter)
  File "/mnt/d/__EXPERIMENTS__/RoIPoly/detectron2/detectron2/engine/train_loop.py", line 155, in train
    self.run_step()
  File "/mnt/d/__EXPERIMENTS__/RoIPoly/detectron2/detectron2/engine/defaults.py", line 530, in run_step
    self._trainer.run_step()
  File "/mnt/d/__EXPERIMENTS__/RoIPoly/detectron2/detectron2/engine/train_loop.py", line 310, in run_step
    loss_dict = self.model(data)
  File "/home/tkk/miniconda3/envs/roipoly_cu111/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/d/__EXPERIMENTS__/PolyR-CNN/polyrcnn/detector.py", line 153, in forward
    loss_dict = self.criterion(output, targets)
  File "/home/tkk/miniconda3/envs/roipoly_cu111/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/d/__EXPERIMENTS__/PolyR-CNN/polyrcnn/loss.py", line 257, in forward
    l_dict = self.get_loss(loss, aux_outputs, targets, indices, **kwargs)
  File "/mnt/d/__EXPERIMENTS__/PolyR-CNN/polyrcnn/loss.py", line 219, in get_loss
    return loss_map[loss](outputs, targets, indices, **kwargs)
TypeError: loss_labels() got an unexpected keyword argument 'log'
```

**Comment by HeinzJiao** [comment]
Thank you for your interest in our work. You can now download the latest version of the code. I have made the necessary modifications, and this bug has been fixed.

**Comment by hcscysh** [comment]
@HeinzJiao Download the latest version of the code,but the bug is also existed
